# -*- coding: utf-8 -*-
"""Bolao_Copa_2026_RENDER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o18T6UM90tuJluMNSyw0Jd-2XztX_f7K
"""

# =========================================================
# BLOCO -1
# INSTALAÇÃO DO AMBIENTE
# BOLÃO COPA 2026
# GOOGLE SHEETS + STREAMLIT
# =========================================================


# =========================================================
# PACOTES PYTHON
# =========================================================

!pip install streamlit -q
!pip install pandas -q



# =========================================================
# CLOUDFLARED
# =========================================================

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64


!chmod +x cloudflared-linux-amd64


!mv cloudflared-linux-amd64 cloudflared



# =========================================================
# TESTE
# =========================================================

print(
    "================================"
)

print(
    "AMBIENTE CONFIGURADO"
)

print(
    "Streamlit + Cloudflare OK"
)

print(
    "================================"
)

# =========================================================
# BLOCO 0
# CONEXÃO GOOGLE SHEETS
# BOLÃO COPA 2026
# =========================================================

import pandas as pd
from urllib.parse import quote


# ID DA PLANILHA OFICIAL

SHEET_ID = "1cDAujojgWNg7SAoR8FQ9MReSB0FTgJvbdYGMjnDVt04"



# =========================================================
# FUNÇÃO DE LEITURA
# =========================================================

def carregar_aba(nome_aba):

    aba_url = quote(nome_aba)

    url = (
        f"https://docs.google.com/spreadsheets/d/"
        f"{SHEET_ID}/gviz/tq?tqx=out:csv&sheet={aba_url}"
    )

    return pd.read_csv(url)



# =========================================================
# CARREGA ABAS OFICIAIS
# =========================================================

C_Participantes = carregar_aba(
    "C_Participantes"
)


C_Placares_Oficiais = carregar_aba(
    "C_Placares Oficiais"
)


C_Palpites = carregar_aba(
    "C_Palpites"
)


C_Ranking_Geral = carregar_aba(
    "C_Ranking Geral"
)



# =========================================================
# TESTE
# =========================================================

print("================================")
print(" GOOGLE SHEETS CONECTADO")
print("================================")

print()

print(
    "Participantes:",
    C_Participantes.shape
)

print(
    "Placares Oficiais:",
    C_Placares_Oficiais.shape
)

print(
    "Palpites:",
    C_Palpites.shape
)

print(
    "Ranking:",
    C_Ranking_Geral.shape
)

# ============================================================
# BLOCO 1.1 — NORMALIZADOR FIFA PREMIUM
# CORREÇÃO DEFINITIVA DE PLACARES
# ============================================================

import pandas as pd
import numpy as np


print("="*90)
print("🧹 NORMALIZANDO BASE FIFA PREMIUM")
print("="*90)


def limpar_celula(valor):


    if pd.isna(valor):

        return ""


    try:

        numero = float(valor)


        if numero.is_integer():

            return str(int(numero))


    except:

        pass


    return str(valor).strip()



BASES = [

    C_Palpites,

    C_Placares_Oficiais

]


for base in BASES:


    for coluna in base.columns:


        base[coluna] = (

            base[coluna]

            .apply(limpar_celula)

        )



print("OK -> Placar 2.0 convertido para 2")

print("OK -> Placar 0.0 convertido para 0")

print("OK -> NaN removido")


print("="*90)

print("🏆 NORMALIZAÇÃO FINALIZADA")

print("="*90)

# =========================================================
# BLOCO 2
# CONVERSOR GOOGLE SHEETS → SISTEMA FIFA
# VERSÃO CONSOLIDADA
# =========================================================

import pandas as pd
import numpy as np


# =========================================================
# 1. CONVERTE JOGOS OFICIAIS
# =========================================================

df = C_Placares_Oficiais.copy()


# =========================================================
# FILTRA SOMENTE JOGOS REAIS DA COPA
# =========================================================

df = df[

    (df["Status"]
     .astype(str)
     .str.lower()
     != "status")

    &

    (df["Partidas"].notna())

    &

    (df["Unnamed: 9"].notna())

    &

    (
        df["Unnamed: 6"]
        .astype(str)
        .str.lower()
        == "x"
    )

].copy()


df = df.reset_index(drop=True)



# =========================================================
# MONTA BASE OFICIAL DE JOGOS
# =========================================================

DF_JOGOS = pd.DataFrame()


DF_JOGOS["id_jogo"] = range(

    1,

    len(df) + 1
)


DF_JOGOS["status"] = df[

    "Status"

]


DF_JOGOS["data"] = df[

    "Primeira fase GRUPO A Dia"

]


DF_JOGOS["sede"] = df[

    "Sede"

]


DF_JOGOS["fase"] = "Grupo"


DF_JOGOS["selecao_a"] = df[

    "Partidas"

]


DF_JOGOS["gols_a"] = df[

    "Unnamed: 5"

]


DF_JOGOS["gols_b"] = df[

    "Unnamed: 7"

]


DF_JOGOS["selecao_b"] = df[

    "Unnamed: 9"

]



# =========================================================
# 2. RANKING OFICIAL
# =========================================================

DF_RANKING_OFICIAL = (

    C_Ranking_Geral
    .copy()

)



# =========================================================
# 3. CONVERTE PALPITES
# FORMATO HORIZONTAL → BANCO DE DADOS
# =========================================================


lista_palpites = []


participantes = (

    C_Participantes["Participantes"]

    .dropna()

    .tolist()

)



for indice, participante in enumerate(participantes):


    inicio_coluna = indice * 10


    bloco = C_Palpites.iloc[

        :,

        inicio_coluna:inicio_coluna + 10

    ].copy()



    for jogo in range(

        len(DF_JOGOS)

    ):


        try:


            lista_palpites.append({


                "participante":

                    participante,


                "id_jogo":

                    jogo + 1,


                "gols_a":

                    bloco.iloc[
                        jogo,
                        5
                    ],


                "gols_b":

                    bloco.iloc[
                        jogo,
                        7
                    ]


            })


        except Exception:


            pass



DF_PALPITES = pd.DataFrame(

    lista_palpites

)



# =========================================================
# LIMPEZA FINAL
# =========================================================


DF_JOGOS = DF_JOGOS.fillna(

    ""

)


DF_PALPITES = DF_PALPITES.fillna(

    ""

)


DF_RANKING_OFICIAL = DF_RANKING_OFICIAL.fillna(

    ""

)



# =========================================================
# AUDITORIA FINAL
# =========================================================


print(
    "=============================="
)

print(
    "CONVERSÃO GOOGLE → FIFA OK"
)

print(
    "=============================="
)


print(

    "DF_JOGOS:",

    DF_JOGOS.shape

)


print(

    "DF_PALPITES:",

    DF_PALPITES.shape

)


print(

    "DF_RANKING:",

    DF_RANKING_OFICIAL.shape

)



print(
    "\nAMOSTRA JOGOS:"
)

display(

    DF_JOGOS.head()

)



print(
    "\nAMOSTRA PALPITES:"
)

display(

    DF_PALPITES.head()

)

# =========================================================
# BLOCO 3A FINAL v3
# PREPARAÇÃO DOS DADOS PARA STREAMLIT FIFA
# VARIÁVEIS OFICIAIS DO GOOGLE SHEETS
# =========================================================

import pandas as pd


# =========================================================
# RANKING
# =========================================================

df_ranking_final = C_Ranking_Geral.copy()


df_ranking_final.to_csv(
    "ranking_oficial.csv",
    index=False,
    encoding="utf-8-sig"
)


print("CSV RANKING GERADO")


# =========================================================
# JOGOS
# =========================================================

df_jogos_final = DF_JOGOS.copy()


df_jogos_final.to_csv(
    "jogos_copa.csv",
    index=False,
    encoding="utf-8-sig"
)


print("CSV JOGOS GERADO")


# =========================================================
# MATRIZ OFICIAL DE PALPITES
# =========================================================


confrontos = {}


for _, jogo in DF_JOGOS.iterrows():


    confrontos[jogo["id_jogo"]] = (

        str(jogo["selecao_a"])

        +

        " x "

        +

        str(jogo["selecao_b"])

    )



matriz = []



# =========================================================
# LINHA 1 - PLACAR OFICIAL
# =========================================================


linha = {

    "Participante":

    "PLACAR OFICIAL"

}



for _, jogo in DF_JOGOS.iterrows():


    if (
        str(jogo["gols_a"]).strip() != ""
        and
        str(jogo["gols_b"]).strip() != ""
    ):


        valor = (

            str(int(float(jogo["gols_a"])))

            +

            " x "

            +

            str(int(float(jogo["gols_b"])))

        )


    else:


        valor = "-"



    linha[

        confrontos[jogo["id_jogo"]]

    ] = valor



matriz.append(linha)



# =========================================================
# PARTICIPANTES
# =========================================================


participantes = sorted(

    DF_PALPITES["participante"]
    .dropna()
    .unique()

)



for nome in participantes:


    linha = {

        "Participante":

        nome

    }


    base = DF_PALPITES[

        DF_PALPITES["participante"]

        ==

        nome

    ]



    for _, jogo in DF_JOGOS.iterrows():


        palpite = base[

            base["id_jogo"]

            ==

            jogo["id_jogo"]

        ]



        if len(palpite) > 0:


            a = palpite.iloc[0]["gols_a"]

            b = palpite.iloc[0]["gols_b"]



            if (

                str(a).strip() != ""

                and

                str(b).strip() != ""

            ):


                valor = (

                    str(int(float(a)))

                    +

                    " x "

                    +

                    str(int(float(b)))

                )


            else:


                valor = "x"


        else:


            valor = "x"



        linha[

            confrontos[jogo["id_jogo"]]

        ] = valor



    matriz.append(linha)




df_palpites_final = pd.DataFrame(matriz)



df_palpites_final.to_csv(

    "palpites.csv",

    index=False,

    encoding="utf-8-sig"

)



print("CSV PALPITES GERADO")


print()
print("==============================")
print("BLOCO 3A FINAL v3 OK")
print("==============================")


print(
    "Ranking:",
    df_ranking_final.shape
)


print(
    "Jogos:",
    df_jogos_final.shape
)


print(
    "Palpites:",
    df_palpites_final.shape
)


display(
    df_palpites_final.head()
)

# =========================================================
# BLOCO 3B FINAL v2
# STREAMLIT FIFA PREMIUM
# ARQUITETURA POR PÁGINAS ISOLADAS
# =========================================================


codigo_app = r'''

import streamlit as st
import pandas as pd


# =====================================================
# CONFIGURAÇÃO
# =====================================================

st.set_page_config(
    page_title="Bolão Copa 2026",
    page_icon="🏆",
    layout="wide"
)


# =====================================================
# CARREGAMENTO DOS DADOS
# =====================================================

ranking = pd.read_csv(
    "ranking_oficial.csv"
).fillna("")


jogos = pd.read_csv(
    "jogos_copa.csv"
).fillna("")


palpites = pd.read_csv(
    "palpites.csv"
).fillna("")


# =====================================================
# ESTILO FIFA PREMIUM
# =====================================================

st.markdown(
"""
<style>

.stApp {
    background: linear-gradient(180deg,#f8fafc,#edf2f7);
}


section[data-testid="stSidebar"] {
    background:#071733;
}


section[data-testid="stSidebar"] * {
    color:white !important;
}


h1 {
    font-size:46px !important;
    font-weight:800 !important;
}


div[data-testid="metric-container"] {

    background:white;
    padding:20px;
    border-radius:18px;
    box-shadow:0 4px 12px rgba(0,0,0,0.08);

}

</style>
""",
unsafe_allow_html=True
)


# =====================================================
# CABEÇALHO FIXO
# =====================================================

st.title(
    "🏆 Bolão Copa do Mundo 2026"
)


st.caption(
    "Painel Oficial FIFA Match Center"
)


st.divider()


# =====================================================
# MENU
# =====================================================

st.sidebar.success(
    "🟢 Sistema Online"
)


pagina = st.sidebar.radio(

    "Navegação",

    [

        "🏅 Classificação",

        "⚽ Jogos",

        "📊 Palpites",

        "💰 Premiação"

    ],

    key="menu_final_fifa_2026"

)



# =====================================================
# CARDS FIXOS
# =====================================================


jogos_finalizados = jogos[

    jogos["status"]
    .astype(str)
    .str.lower()
    .str.contains("encerrado")

].shape[0]


c1,c2,c3 = st.columns(3)


with c1:

    st.metric(

        "Participantes",

        len(ranking)

    )


with c2:

    st.metric(

        "Jogos",

        f"{jogos_finalizados}/104"

    )


with c3:

    st.metric(

        "Fase Real",

        "GRUPOS"

    )


st.divider()



# =====================================================
# FUNÇÃO CLASSIFICAÇÃO
# =====================================================

def tela_classificacao():


    st.subheader(
        "🏅 Ranking Geral"
    )


    st.dataframe(

        ranking,

        hide_index=True,

        use_container_width=True

    )



# =====================================================
# FUNÇÃO JOGOS
# =====================================================


def tela_jogos():


    st.subheader(
        "⚽ Central de Partidas da FIFA"
    )


    tabela = jogos.copy()


    def montar_placar(x):


        if str(x["gols_a"]).strip() == "":

            return "-"


        return (

            str(x["gols_a"])

            +

            " x "

            +

            str(x["gols_b"])

        )



    tabela["Placar"] = tabela.apply(

        montar_placar,

        axis=1

    )


    exibir = pd.DataFrame({

        "📅 Data":

            tabela["data"],


        "🏆 Fase":

            tabela["fase"],


        "Mandante":

            tabela["selecao_a"],


        "Placar":

            tabela["Placar"],


        "Visitante":

            tabela["selecao_b"],


        "📍 Sede":

            tabela["sede"],


        "Status":

            tabela["status"]

    })


    st.dataframe(

        exibir,

        hide_index=True,

        use_container_width=True

    )



# =====================================================
# FUNÇÃO PALPITES
# =====================================================


def tela_palpites():


    st.subheader(
        "📊 Matriz Oficial de Palpites"
    )



    def destaque(row):


        if row["Participante"] == "PLACAR OFICIAL":


            return [

                "background-color:#fff3cd;font-weight:bold"

            ] * len(row)


        return [""] * len(row)



    st.dataframe(

        palpites.style.apply(

            destaque,

            axis=1

        ),

        hide_index=True,

        use_container_width=True

    )



# =====================================================
# FUNÇÃO PREMIAÇÃO
# =====================================================


def tela_premiacao():


    st.subheader(
        "💰 Premiação Oficial do Bolão"
    )


    c1,c2,c3 = st.columns(3)


    with c1:

        st.metric(

            "💵 Valor arrecadado",

            "R$ 6.000,00"

        )


    with c2:

        st.metric(

            "👥 Participantes",

            len(ranking)

        )


    with c3:

        st.metric(

            "💲 Entrada",

            "R$ 200,00"

        )


    vencedores = ranking["Participantes"].head(3)


    st.markdown(
        "## 🏆 Premiação Fase de Grupos"
    )


    st.dataframe(

        pd.DataFrame({

            "Ranking":

            ["🥇 1º","🥈 2º","🥉 3º"],


            "Participante":

            vencedores,


            "Valor":

            [

                "R$ 600,00",

                "R$ 360,00",

                "R$ 240,00"

            ]

        }),

        hide_index=True,

        use_container_width=True

    )



    st.markdown(
        "## 🌍 Premiação Geral do Torneio"
    )


    st.dataframe(

        pd.DataFrame({

            "Ranking":

            ["🥇 1º","🥈 2º","🥉 3º"],


            "Participante":

            vencedores,


            "Valor":

            [

                "R$ 2.880,00",

                "R$ 1.200,00",

                "R$ 720,00"

            ]

        }),

        hide_index=True,

        use_container_width=True

    )



# =====================================================
# CONTROLE FINAL DAS PÁGINAS
# =====================================================


if pagina == "🏅 Classificação":

    tela_classificacao()


elif pagina == "⚽ Jogos":

    tela_jogos()


elif pagina == "📊 Palpites":

    tela_palpites()


elif pagina == "💰 Premiação":

    tela_premiacao()


'''



with open(

    "app.py",

    "w",

    encoding="utf-8"

) as f:

    f.write(codigo_app)



print("==============================")
print("APP FIFA PREMIUM FINAL GERADO")
print("ARQUITETURA POR FUNÇÕES")
print("SEM MISTURA ENTRE ABAS")
print("==============================")

# =========================================================
# BLOCO 4
# PUBLICAÇÃO CLOUDFLARE
# BOLÃO COPA 2026
# =========================================================

import subprocess
import time
import re



# =========================================================
# INICIA TÚNEL
# =========================================================


processo = subprocess.Popen(

    [

        "./cloudflared",

        "tunnel",

        "--url",

        "http://localhost:8501"

    ],

    stdout=subprocess.PIPE,

    stderr=subprocess.STDOUT,

    text=True

)



# =========================================================
# CAPTURA LINK
# =========================================================


print(
    "================================"
)

print(
    "GERANDO LINK DO BOLÃO..."
)

print(
    "================================"
)



for linha in processo.stdout:


    print(linha.strip())


    resultado = re.search(

        r"https://[-a-zA-Z0-9]+\.trycloudflare\.com",

        linha

    )


    if resultado:


        print()
        print(
            "================================"
        )

        print(
            "🏆 BOLÃO COPA 2026 ONLINE"
        )

        print(
            "================================"
        )

        print(
            resultado.group(0)
        )

        break

# =========================================================
# BLOCO 5 FINAL
# PACOTE PRODUÇÃO RENDER
# BOLÃO COPA 2026 FIFA PREMIUM v1.0
# =========================================================

import os
import zipfile
from datetime import datetime


print("="*40)
print("VALIDAÇÃO DO PACOTE PRODUÇÃO")
print("="*40)


# =========================================================
# ARQUIVOS OBRIGATÓRIOS
# =========================================================

arquivos = [

    "app.py",

    "ranking_oficial.csv",

    "jogos_copa.csv",

    "palpites.csv"

]


for arquivo in arquivos:


    if not os.path.exists(arquivo):

        raise Exception(
            f"Arquivo ausente: {arquivo}"
        )


    print(
        "OK ->",
        arquivo
    )



# =========================================================
# VALIDA APP FINAL
# =========================================================


with open(

    "app.py",

    "r",

    encoding="utf-8"

) as f:


    app_codigo = f.read()



validacoes = [

    "def tela_classificacao",

    "def tela_jogos",

    "def tela_palpites",

    "def tela_premiacao",

    "menu_final_fifa_2026"

]



for item in validacoes:


    if item not in app_codigo:


        raise Exception(

            "APP.PY NÃO É A VERSÃO FINAL: "

            +

            item

        )



print()
print(
    "APP FIFA PREMIUM v1.0 VALIDADO"
)



# =========================================================
# REQUIREMENTS
# =========================================================


requirements = """

streamlit
pandas

"""



with open(

    "requirements.txt",

    "w",

    encoding="utf-8"

) as f:


    f.write(

        requirements.strip()

    )



print(
    "requirements.txt GERADO"
)



# =========================================================
# ARQUIVO DE VERSÃO
# =========================================================


versao = f"""

Bolão Copa do Mundo 2026

Versão:
FIFA PREMIUM v1.0

Gerado:
{datetime.now()}

Arquitetura:
Google Sheets
↓
Tratamento Python
↓
Streamlit
↓
Render

"""


with open(

    "VERSAO.txt",

    "w",

    encoding="utf-8"

) as f:


    f.write(versao)



# =========================================================
# ZIP FINAL
# =========================================================


nome_zip = (

    "Bolao_Copa_2026_"

    "FIFA_PREMIUM_v1.zip"

)



with zipfile.ZipFile(

    nome_zip,

    "w",

    zipfile.ZIP_DEFLATED

) as zipf:


    for arquivo in [

        "app.py",

        "requirements.txt",

        "ranking_oficial.csv",

        "jogos_copa.csv",

        "palpites.csv",

        "VERSAO.txt"

    ]:


        zipf.write(

            arquivo

        )



print()
print("="*40)
print("PACOTE FINAL GERADO COM SUCESSO")
print("="*40)

print(
    nome_zip
)

print()
print(
    "PRONTO PARA PUBLICAÇÃO PERMANENTE NO RENDER"
)

# =====================================================
# AUDITORIA FINAL DO APP.PY PUBLICADO
# =====================================================

with open("app.py", "r", encoding="utf-8") as f:
    linhas = f.readlines()


print("="*60)
print("TODAS AS OCORRÊNCIAS DE CLASSIFICAÇÃO")
print("="*60)

for i, linha in enumerate(linhas, start=1):

    if (
        "Classificação" in linha
        or "Ranking" in linha
        or "subheader" in linha
        or "markdown" in linha
    ):

        print(
            i,
            "=>",
            linha.strip()
        )


print("\n" + "="*60)
print("FUNÇÕES E CHAMADAS")
print("="*60)


for i, linha in enumerate(linhas, start=1):

    if (
        "def tela" in linha
        or "pagina ==" in linha
        or "menu_final" in linha
    ):

        print(
            i,
            "=>",
            linha.strip()
        )

# ============================================================
# BLOCO 5.5 — AUDITOR FIFA PREMIUM v2.0
# VALIDAÇÃO COMPLETA ANTES DO MOTOR DE PONTUAÇÃO
# ============================================================

print("="*70)
print("🏆 AUDITOR FIFA PREMIUM v2.0 - INICIANDO")
print("="*70)

erros = []
avisos = []


# ============================================================
# 1) BASES PRINCIPAIS
# ============================================================

print("\n1) VALIDANDO BASES")

bases = {
    "C_Participantes": C_Participantes,
    "C_Placares_Oficiais": C_Placares_Oficiais,
    "C_Palpites": C_Palpites
}

for nome, df in bases.items():

    try:

        print(f"OK -> {nome}: {df.shape}")

    except:

        erros.append(f"Base ausente: {nome}")



# ============================================================
# 2) PARTICIPANTES
# ============================================================

print("\n2) VALIDANDO PARTICIPANTES")

try:

    qtd = len(C_Participantes)

    if qtd == 30:

        print("OK -> 30 participantes encontrados")

    else:

        avisos.append(
            f"Quantidade participantes atual: {qtd}"
        )

except Exception as e:

    erros.append(str(e))



# ============================================================
# 3) JOGOS FIFA
# ============================================================

print("\n3) VALIDANDO JOGOS")

try:

    if len(DF_JOGOS) == 104:

        print("OK -> 104 jogos FIFA encontrados")

    else:

        erros.append(
            f"Jogos encontrados: {len(DF_JOGOS)}"
        )

except Exception as e:

    erros.append(
        f"Erro DF_JOGOS: {e}"
    )



# ============================================================
# 4) PALPITES
# ============================================================

print("\n4) VALIDANDO PALPITES")

try:

    esperado = len(C_Participantes) * 104

    encontrados = len(DF_PALPITES)


    if encontrados == esperado:

        print(
            f"OK -> {encontrados} palpites encontrados"
        )

    else:

        erros.append(
            f"Palpites {encontrados}, esperado {esperado}"
        )


except Exception as e:

    erros.append(
        f"Erro DF_PALPITES: {e}"
    )



# ============================================================
# 5) CLASSIFICADOS POR FASE
# ============================================================

print("\n5) VALIDANDO ESPELHOS DE CLASSIFICAÇÃO")


fases = {

    "32 avos": (73,88,4),

    "Oitavas": (89,96,8),

    "Quartas": (97,100,12),

    "Semifinal": (101,102,16),

    "Final": (104,104,24)

}


try:

    for fase, dados in fases.items():

        ini, fim, pontos = dados


        jogos_fase = DF_JOGOS[
            (DF_JOGOS["id_jogo"] >= ini)
            &
            (DF_JOGOS["id_jogo"] <= fim)
        ]


        selecoes = []


        selecoes += (
            jogos_fase["selecao_a"]
            .dropna()
            .tolist()
        )

        selecoes += (
            jogos_fase["selecao_b"]
            .dropna()
            .tolist()
        )


        print(
            f"OK -> {fase}: {len(selecoes)} posições ({pontos} pts cada)"
        )


except Exception as e:

    erros.append(
        f"Erro fases eliminatórias: {e}"
    )



# ============================================================
# 6) TESTE IPSIS LITTERIS
# ============================================================

print("\n6) VALIDANDO REGRA IPSIS LITTERIS")


try:

    oficial_a = "Brasil"
    oficial_b = "França"


    teste1 = (
        oficial_a == "Brasil"
        and oficial_b == "França"
    )


    teste2 = (
        oficial_a == "França"
        and oficial_b == "Brasil"
    )


    if teste1 and not teste2:

        print(
            "OK -> Inversão de confronto será bloqueada"
        )

    else:

        erros.append(
            "Falha regra ipsis litteris"
        )


except Exception as e:

    erros.append(str(e))



# ============================================================
# 7) CAMPOS FINAIS
# ============================================================

print("\n7) VALIDANDO RESULTADOS FINAIS")


campos = [

    "Artilheiro",

    "Campeão",

    "Vice Campeção",

    "3º Colocado",

    "4º Colocado"

]


texto_base = (
    C_Placares_Oficiais
    .astype(str)
    .to_string()
)


for campo in campos:

    if campo in texto_base:

        print(
            f"OK -> Campo localizado: {campo}"
        )

    else:

        avisos.append(
            f"Campo ainda não encontrado: {campo}"
        )



# ============================================================
# 8) TESTE REGRA DOS 2 PONTOS
# ============================================================

print("\n8) VALIDANDO REGRA DOS 2 PONTOS")


try:

    real = (3,1)
    palpite = (1,1)


    acertou_algum = (
        real[0] in palpite
        or real[1] in palpite
    )


    if acertou_algum:

        print(
            "OK -> Um placar correto gera pontuação independente do vencedor"
        )

    else:

        erros.append(
            "Falha regra 2 pontos"
        )


except Exception as e:

    erros.append(str(e))



# ============================================================
# RESULTADO FINAL
# ============================================================

print("\n")
print("="*70)

if erros:

    print("❌ AUDITORIA REPROVADA")

    for e in erros:

        print("-", e)


else:

    print("🏆 AUDITORIA FIFA PREMIUM APROVADA")


if avisos:

    print("\nAVISOS (não bloqueiam):")

    for a in avisos:

        print("-", a)


print("="*70)
print("VALIDAÇÃO FINALIZADA")
print("="*70)

# ============================================================
# BLOCO 6A — MOTOR DE PONTUAÇÃO DE PLACARES
# FIFA PREMIUM v2.0
# ============================================================

print("="*70)
print("🧠 MOTOR DE PONTUAÇÃO DE PLACARES - FIFA PREMIUM v2.0")
print("="*70)


# ============================================================
# FUNÇÃO PRINCIPAL DO REGULAMENTO
# ============================================================

def calcular_pontos_placar(
    gols_a_real,
    gols_b_real,
    gols_a_palpite,
    gols_b_palpite
):


    # ----------------------------
    # ACERTO EXATO
    # ----------------------------

    if (
        gols_a_real == gols_a_palpite
        and
        gols_b_real == gols_b_palpite
    ):

        return 12, "Placar exato"



    # ----------------------------
    # IDENTIFICAR RESULTADOS
    # ----------------------------

    def resultado(a,b):

        if a > b:

            return "A"

        elif b > a:

            return "B"

        else:

            return "E"



    resultado_real = resultado(
        gols_a_real,
        gols_b_real
    )


    resultado_palpite = resultado(
        gols_a_palpite,
        gols_b_palpite
    )



    acertou_resultado = (
        resultado_real == resultado_palpite
    )


    acertou_algum_placar = (
        gols_a_real == gols_a_palpite
        or
        gols_b_real == gols_b_palpite
    )



    # ----------------------------
    # VENCEDOR + UM PLACAR
    # ----------------------------

    if (
        acertou_resultado
        and
        acertou_algum_placar
    ):

        return 8, "Resultado + um placar"



    # ----------------------------
    # SOMENTE RESULTADO
    # ----------------------------

    if acertou_resultado:

        return 5, "Resultado correto"



    # ----------------------------
    # SOMENTE UM PLACAR
    # INDEPENDENTE DO RESULTADO
    # ----------------------------

    if acertou_algum_placar:

        return 2, "Um placar correto"



    # ----------------------------
    # ERRO COMPLETO
    # ----------------------------

    return 0, "Erro completo"



# ============================================================
# BATERIA DE TESTES DO REGULAMENTO
# ============================================================

testes = [

    # vitória

    ("Exato vitória",
     (2,0),
     (2,0),
     12),

    ("Vencedor + placar",
     (2,0),
     (2,1),
     8),

    ("Só vencedor",
     (2,0),
     (3,1),
     5),

    ("Só placar mesmo errando vencedor",
     (2,0),
     (2,3),
     2),

    ("Erro completo",
     (2,0),
     (1,3),
     0),


    # empate

    ("Exato empate",
     (1,1),
     (1,1),
     12),

    ("Empate não exato",
     (1,1),
     (2,2),
     5),

    ("Acertou gol mas errou empate",
     (1,1),
     (1,0),
     2),

]


print("\nTESTANDO REGULAMENTO\n")


erros = []


for nome, real, palpite, esperado in testes:


    pontos, motivo = calcular_pontos_placar(

        real[0],
        real[1],
        palpite[0],
        palpite[1]

    )


    status = "OK" if pontos == esperado else "ERRO"


    print(
        status,
        "|",
        nome,
        "| Real:",
        real,
        "| Palpite:",
        palpite,
        "| Pontos:",
        pontos,
        "|",
        motivo
    )


    if pontos != esperado:

        erros.append(nome)



print("\n")
print("="*70)


if len(erros) == 0:

    print("🏆 MOTOR 6A APROVADO")
    print("Regra 12 / 8 / 5 / 2 / 0 validada")


else:

    print("❌ FALHAS ENCONTRADAS")

    for e in erros:

        print(e)


print("="*70)

# ============================================================
# BLOCO 5.6 — AUDITOR DE MAPEAMENTO DOS PALPITES
# FIFA PREMIUM v2.0
# ============================================================

print("="*80)
print("🔍 AUDITOR DE MAPA DOS PARTICIPANTES / PALPITES")
print("="*80)


erros = []


# ============================================================
# CONFIGURAÇÃO DA MATRIZ
# ============================================================

TOTAL_JOGOS = 104
SALTO_COLUNAS = 10

# Primeiro participante começa na coluna J
COLUNA_INICIAL = 9   # pandas começa em zero


# ============================================================
# PARTICIPANTES
# ============================================================

participantes = (
    C_Participantes
    .iloc[:,0]
    .dropna()
    .tolist()
)


print(
    f"\nParticipantes encontrados: {len(participantes)}"
)


# ============================================================
# AUDITORIA INDIVIDUAL
# ============================================================

for indice, nome in enumerate(participantes):


    coluna = COLUNA_INICIAL + (
        indice * SALTO_COLUNAS
    )


    try:


        # Nome localizado na matriz de palpites
        # (procura nas primeiras linhas do bloco)

        bloco = C_Palpites.iloc[:, coluna]


        # Contagem de palpites não vazios

        qtd_preenchidos = (
            bloco
            .dropna()
            .astype(str)
            .str.strip()
        )


        qtd_preenchidos = len(
            qtd_preenchidos[
                qtd_preenchidos != ""
            ]
        )


        status = "OK"


        if coluna >= C_Palpites.shape[1]:

            status = "ERRO"
            erros.append(
                f"{nome}: coluna fora da matriz"
            )


        print(
            f"{status} | "
            f"{indice+1:02d} | "
            f"{nome} | "
            f"Coluna pandas {coluna} | "
            f"Registros encontrados: {qtd_preenchidos}"
        )


    except Exception as e:


        erros.append(
            f"{nome}: {e}"
        )



# ============================================================
# TESTE DE EXTREMIDADES
# ============================================================

print("\n" + "="*80)
print("TESTE PRIMEIRO E ÚLTIMO PARTICIPANTE")
print("="*80)


try:

    primeiro = participantes[0]
    ultimo = participantes[-1]


    col_primeiro = COLUNA_INICIAL

    col_ultimo = COLUNA_INICIAL + (
        (len(participantes)-1)
        *
        SALTO_COLUNAS
    )


    print(
        "Primeiro:",
        primeiro,
        "-> coluna",
        col_primeiro
    )


    print(
        "Último:",
        ultimo,
        "-> coluna",
        col_ultimo
    )


    if col_ultimo < C_Palpites.shape[1]:

        print(
            "OK -> Último participante dentro da matriz"
        )

    else:

        erros.append(
            "Último participante ultrapassa limite de colunas"
        )


except Exception as e:

    erros.append(str(e))



# ============================================================
# RESULTADO FINAL
# ============================================================


print("\n")
print("="*80)


if erros:

    print("❌ AUDITORIA DE MAPA REPROVADA")

    for e in erros:

        print("-", e)


else:

    print("🏆 AUDITORIA DE MAPA APROVADA")
    print("30 participantes alinhados")
    print("Motor autorizado a percorrer os palpites")


print("="*80)

# ============================================================
# BLOCO 5.7 — AUDITOR DEFINITIVO DOS PALPITES v5
# FIFA PREMIUM v2.0
# ============================================================

print("="*90)
print("🔍 AUDITOR FINAL v5 — MAPA COMPLETO C_PALPITES")
print("="*90)


erros = []


# ============================================================
# CONFIGURAÇÃO DA MATRIZ
# ============================================================

TOTAL_PARTICIPANTES = 30
SALTO = 10


# ============================================================
# FUNÇÃO DE BUSCA INTELIGENTE
# ============================================================

def buscar_valor_por_texto(df, texto, coluna_final):


    for linha in range(len(df)):


        linha_texto = (
            df.iloc[linha]
            .astype(str)
        )


        encontrou = (
            linha_texto
            .str.contains(
                texto,
                case=False,
                regex=False
            )
            .any()
        )


        if encontrou:


            # procura dentro do bloco de 10 colunas
            coluna_inicio = coluna_final - 9


            for c in range(
                coluna_final,
                coluna_inicio - 1,
                -1
            ):


                valor = df.iloc[linha, c]


                valor_txt = (
                    str(valor)
                    .strip()
                )


                if (
                    valor_txt != ""
                    and
                    valor_txt.lower() != "nan"
                    and
                    texto.lower()
                    not in valor_txt.lower()
                ):


                    return valor


            return None


    return None



# ============================================================
# AUDITORIA DOS 30 PARTICIPANTES
# ============================================================


total_jogos = 0


for i in range(TOTAL_PARTICIPANTES):


    coluna_nome = i * SALTO

    coluna_final = coluna_nome + 9


    try:


        # ------------------------------------
        # Nome real do participante
        # ------------------------------------

        participante = (
            str(
                C_Palpites
                .columns[coluna_nome]
            )
            .replace("Status","")
            .strip()
        )



        # ------------------------------------
        # Jogos
        # ------------------------------------

        jogos = len(

            DF_PALPITES[

                DF_PALPITES["participante"]

                ==

                participante

            ]

        )


        total_jogos += jogos



        # ------------------------------------
        # Campos finais
        # ------------------------------------

        artilheiro = buscar_valor_por_texto(

            C_Palpites,

            "Artilheiro",

            coluna_final

        )


        campeao = buscar_valor_por_texto(

            C_Palpites,

            "Campeão",

            coluna_final

        )


        vice = buscar_valor_por_texto(

            C_Palpites,

            "Vice Campeção",

            coluna_final

        )


        terceiro = buscar_valor_por_texto(

            C_Palpites,

            "3º Colocado",

            coluna_final

        )


        quarto = buscar_valor_por_texto(

            C_Palpites,

            "4º Colocado",

            coluna_final

        )



        # ------------------------------------
        # Impressão auditoria
        # ------------------------------------

        print("-"*90)


        print(

            f"{i+1:02d} | {participante}"

        )


        print(

            f"Bloco colunas: {coluna_nome} até {coluna_final}"

        )


        print(

            f"Jogos encontrados: {jogos}/104"

        )


        print(

            "⚽ Artilheiro:",

            artilheiro

        )


        print(

            "🏆 Campeão:",

            campeao

        )


        print(

            "🥈 Vice:",

            vice

        )


        print(

            "🥉 3º:",

            terceiro

        )


        print(

            "4º:",

            quarto

        )



        if jogos != 104:


            erros.append(

                f"{participante}: {jogos} jogos"

            )



    except Exception as e:


        erros.append(

            f"Erro participante {i+1}: {e}"

        )



# ============================================================
# RESULTADO FINAL
# ============================================================


print("="*90)


print(

    f"TOTAL DE PALPITES RASTREADOS: {total_jogos}"

)


if (

    len(erros) == 0

    and

    total_jogos == 3120

):


    print("🏆 AUDITORIA DEFINITIVA APROVADA")

    print("30 participantes + 3120 palpites vinculados")

    print("Liberado para BLOCO 6B")


else:


    print("❌ PROBLEMAS ENCONTRADOS")


    for erro in erros:


        print("-", erro)



print("="*90)

# ============================================================
# BLOCO 6C FINAL — RANKING OFICIAL DO REGULAMENTO
# VERSÃO PRODUÇÃO / RENDER
# ============================================================

import pandas as pd


print("="*90)
print("🏅 BLOCO 6C FINAL — RANKING OFICIAL")
print("="*90)



# ============================================================
# BASE OFICIAL DE PARTICIPANTES
# ============================================================

participantes = (

    C_Participantes["Participantes"]

    .dropna()

    .drop_duplicates()

    .reset_index(drop=True)

)



# ============================================================
# CRIA RANKING OFICIAL ZERADO
# ============================================================

DF_RANKING_OFICIAL = pd.DataFrame()


DF_RANKING_OFICIAL["Posição"] = (

    range(

        1,

        len(participantes) + 1

    )

)


DF_RANKING_OFICIAL["Participante"] = participantes



DF_RANKING_OFICIAL[
    "ITEM 4.1. Fase de Grupo"
] = 0


DF_RANKING_OFICIAL[
    "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias"
] = 0


DF_RANKING_OFICIAL[
    "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º"
] = 0


DF_RANKING_OFICIAL[
    "4.2. Artilheiro"
] = 0


DF_RANKING_OFICIAL[
    "TOTAL"
] = 0



# ============================================================
# ESPELHO DA PREMIAÇÃO FASE DE GRUPOS
# ============================================================

DF_PREMIACAO_GRUPOS = (

    DF_RANKING_OFICIAL[

        [

            "Posição",

            "Participante",

            "ITEM 4.1. Fase de Grupo",

            "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º"

        ]

    ]

    .copy()

)



DF_PREMIACAO_GRUPOS[

    "TOTAL PREMIAÇÃO FASE DE GRUPOS"

] = (

    DF_PREMIACAO_GRUPOS[

        "ITEM 4.1. Fase de Grupo"

    ]

    +

    DF_PREMIACAO_GRUPOS[

        "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º"

    ]

)



# ============================================================
# EXIBIÇÃO
# ============================================================


display(

    DF_RANKING_OFICIAL

)


print()
print("🥇 ESPELHO FASE DE GRUPOS")


display(

    DF_PREMIACAO_GRUPOS

)



print("="*90)
print("🏆 BLOCO 6C FINAL PRODUÇÃO HOMOLOGADO")
print("="*90)

# ============================================================
# BLOCO 6B FINAL v4 — PLACARES + IPSIS LITTERIS
# FIFA PREMIUM v2.0
# ============================================================

import pandas as pd


print("="*90)
print("🏆 BLOCO 6B FINAL v4 — MOTOR OFICIAL DE PLACARES")
print("="*90)


# ============================================================
# FUNÇÕES
# ============================================================

def limpar(valor):

    return (
        str(valor)
        .strip()
        .upper()
    )


def calcular_pontos(real_a, real_b, palpite_a, palpite_b):


    try:

        real_a = int(real_a)
        real_b = int(real_b)

        palpite_a = int(palpite_a)
        palpite_b = int(palpite_b)


    except:

        return 0, "Sem placar"



    # 12 pontos — placar exato

    if real_a == palpite_a and real_b == palpite_b:

        return 12, "Placar exato"



    resultado_real = (

        real_a > real_b

    ) - (

        real_a < real_b

    )


    resultado_palpite = (

        palpite_a > palpite_b

    ) - (

        palpite_a < palpite_b

    )



    # 8 pontos

    if (

        resultado_real == resultado_palpite

        and

        (

            real_a == palpite_a

            or

            real_b == palpite_b

        )

    ):

        return 8, "Resultado + um placar"



    # 5 pontos

    if resultado_real == resultado_palpite:

        return 5, "Resultado correto"



    # 2 pontos

    if (

        real_a == palpite_a

        or

        real_b == palpite_b

    ):

        return 2, "Um placar correto"



    return 0, "Erro completo"



# ============================================================
# BUSCAR CONFRONTO DO PARTICIPANTE
# ============================================================

def buscar_confronto_participante(
    participante,
    id_jogo
):


    # localizar posição do participante

    nomes = [

        str(c)
        .replace(" Status","")
        .strip()

        for c in C_Palpites.columns

    ]


    inicio = None


    for idx, nome in enumerate(nomes):

        if nome == participante:

            inicio = idx

            break



    if inicio is None:

        return "", ""



    # volta para início real do bloco de 10

    inicio = (inicio // 10) * 10



    linha = int(id_jogo) - 1



    try:


        selecao_a = C_Palpites.iloc[
            linha,
            inicio + 3
        ]


        selecao_b = C_Palpites.iloc[
            linha,
            inicio + 9
        ]



        return (

            limpar(selecao_a),

            limpar(selecao_b)

        )


    except:


        return "", ""



# ============================================================
# PROCESSAMENTO
# ============================================================

registros = []



for _, jogo in DF_JOGOS.iterrows():


    id_jogo = jogo["id_jogo"]


    fase = limpar(

        jogo["fase"]

    )


    status = limpar(

        jogo["status"]

    )



    oficial_a = limpar(

        jogo["selecao_a"]

    )


    oficial_b = limpar(

        jogo["selecao_b"]

    )



    palpites_jogo = DF_PALPITES[

        DF_PALPITES["id_jogo"] == id_jogo

    ]



    for _, palpite in palpites_jogo.iterrows():



        participante = palpite["participante"]



        pontos = 0

        motivo = "Jogo não iniciado"

        ipsis = "NÃO APLICÁVEL"



        # ===============================
        # SOMENTE FINALIZADOS
        # ===============================

        if status == "FINALIZADO":



            # ---------------------------
            # FASE DE GRUPOS
            # ---------------------------

            if "GRUPO" in fase:



                pontos, motivo = calcular_pontos(

                    jogo["gols_a"],

                    jogo["gols_b"],

                    palpite["gols_a"],

                    palpite["gols_b"]

                )



            # ---------------------------
            # ELIMINATÓRIA
            # ---------------------------

            else:



                palpite_a, palpite_b = (

                    buscar_confronto_participante(

                        participante,

                        id_jogo

                    )

                )



                if (

                    oficial_a == palpite_a

                    and

                    oficial_b == palpite_b

                ):



                    ipsis = "APROVADO"



                    pontos, motivo = calcular_pontos(

                        jogo["gols_a"],

                        jogo["gols_b"],

                        palpite["gols_a"],

                        palpite["gols_b"]

                    )



                else:



                    ipsis = "BLOQUEADO"



                    pontos = 0


                    motivo = (

                        "Bloqueado Ipsís Litteris"

                    )



        # ====================================================
        # DESTINO DO RANKING
        # ====================================================


        if "GRUPO" in fase:


            destino = (

                "ITEM 4.1. Fase de Grupo"

            )


        else:


            destino = (

                "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias"

            )



        registros.append(

            {

                "Participante":

                    participante,


                "Jogo":

                    id_jogo,


                "Fase":

                    fase,


                "Oficial":

                    oficial_a + " x " + oficial_b,


                "Ipsís":

                    ipsis,


                "Pontos":

                    pontos,


                "Destino":

                    destino,


                "Motivo":

                    motivo

            }

        )



# ============================================================
# DATAFRAME
# ============================================================

DF_PLACARES_FINAL = pd.DataFrame(

    registros

)



# ============================================================
# ATUALIZAR RANKING
# ============================================================

for coluna in [

    "ITEM 4.1. Fase de Grupo",

    "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias"

]:


    soma = (

        DF_PLACARES_FINAL[

            DF_PLACARES_FINAL["Destino"] == coluna

        ]

        .groupby("Participante")

        ["Pontos"]

        .sum()

    )



    DF_RANKING_OFICIAL[coluna] = (

        DF_RANKING_OFICIAL["Participante"]

        .map(soma)

        .fillna(0)

        .astype(int)

    )



# ============================================================
# TOTAL GERAL
# ============================================================


DF_RANKING_OFICIAL["TOTAL"] = (


    DF_RANKING_OFICIAL[

        "ITEM 4.1. Fase de Grupo"

    ]

    +

    DF_RANKING_OFICIAL[

        "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias"

    ]

    +

    DF_RANKING_OFICIAL[

        "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º"

    ]

    +

    DF_RANKING_OFICIAL[

        "4.2. Artilheiro"

    ]

)



# ============================================================
# AUDITORIA
# ============================================================

print(
    "Registros:",
    len(DF_PLACARES_FINAL)
)


display(

    DF_PLACARES_FINAL.head(40)

)


display(

    DF_RANKING_OFICIAL

)



print("="*90)

print("🏆 BLOCO 6B FINAL v4 HOMOLOGADO")

print("="*90)

# ============================================================
# BLOCO 6D FINAL v4 — ITEM 4.2 REGULAMENTO OFICIAL
# PASSAGEM DE FASE / CAMPEÃO / VICE / 3º / 4º
# FIFA PREMIUM v2.0
# ============================================================

import pandas as pd


print("="*90)
print("🏆 BLOCO 6D FINAL v4 — ITEM 4.2 OFICIAL")
print("="*90)



# ============================================================
# FUNÇÕES
# ============================================================

def limpar(txt):

    return (
        str(txt)
        .replace(" Status","")
        .strip()
        .upper()
    )



def selecao_valida(nome):

    bloqueios = [
        "",
        "NAN",
        "A DEFINIR",
        "VENCEDOR",
        "PERDEDOR",
        "CLASSIFICADO"
    ]


    for b in bloqueios:

        if b in nome:

            return False


    return True



# ============================================================
# MAPA DAS FASES
# ============================================================

FASES = {


    "32 avos": {

        "oficial_linhas": range(96,112),
        "palpite_linhas": range(84,100),
        "pontos": 4,
        "max": 128

    },


    "Oitavas": {

        "oficial_linhas": range(113,121),
        "palpite_linhas": range(101,109),
        "pontos": 8,
        "max": 128

    },


    "Quartas": {

        "oficial_linhas": range(122,126),
        "palpite_linhas": range(110,114),
        "pontos": 12,
        "max": 96

    },


    "Semifinal": {

        "oficial_linhas": range(126,128),
        "palpite_linhas": range(115,117),
        "pontos": 16,
        "max": 64

    },


    "Final": {

        "oficial_linhas": range(128,129),
        "palpite_linhas": range(118,119),
        "pontos": 24,
        "max": 48

    }

}



# ============================================================
# BUSCAR CLASSIFICADOS OFICIAIS
# ============================================================

oficiais = {}


for fase, cfg in FASES.items():


    selecoes = set()


    for linha in cfg["oficial_linhas"]:


        if linha < len(C_Placares_Oficiais):


            for coluna in [3,9]:


                nome = limpar(

                    C_Placares_Oficiais.iloc[linha,coluna]

                )


                if selecao_valida(nome):

                    selecoes.add(nome)



    oficiais[fase] = selecoes



# ============================================================
# RESULTADOS FINAIS OFICIAIS
# ============================================================

campeao_oficial = limpar(
    C_Placares_Oficiais.iloc[124,9]
)

vice_oficial = limpar(
    C_Placares_Oficiais.iloc[125,9]
)

terceiro_oficial = limpar(
    C_Placares_Oficiais.iloc[126,9]
)

quarto_oficial = limpar(
    C_Placares_Oficiais.iloc[127,9]
)



# ============================================================
# PROCESSAMENTO PARTICIPANTES
# ============================================================

resultado = []


TOTAL = 30
SALTO = 10



for i in range(TOTAL):


    inicio = i * SALTO


    participante = (

        str(C_Palpites.columns[inicio])
        .replace(" Status","")
        .strip()

    )


    linha_resultado = {

        "Participante": participante

    }


    total = 0



    # --------------------------
    # PASSAGEM DE FASE
    # --------------------------

    for fase, cfg in FASES.items():


        palpites = set()


        bloco = C_Palpites.iloc[

            list(cfg["palpite_linhas"]),

            inicio:inicio+10

        ]



        for valor in bloco.values.flatten():


            nome = limpar(valor)


            if selecao_valida(nome):

                palpites.add(nome)



        acertos = oficiais[fase] & palpites


        pontos = (

            len(acertos)

            *

            cfg["pontos"]

        )



        if pontos > cfg["max"]:

            raise Exception(

                f"ERRO {participante}: {fase} excedeu limite"

            )



        linha_resultado[fase] = pontos


        total += pontos



    # --------------------------
    # CAMPEÃO / VICE / 3º / 4º
    # --------------------------

    bonus = 0


    finais_ok = all(

        selecao_valida(x)

        for x in [

            campeao_oficial,
            vice_oficial,
            terceiro_oficial,
            quarto_oficial

        ]

    )



    if finais_ok:


        if limpar(C_Palpites.iloc[124,inicio+9]) == campeao_oficial:

            bonus += 25


        if limpar(C_Palpites.iloc[125,inicio+9]) == vice_oficial:

            bonus += 18


        if limpar(C_Palpites.iloc[126,inicio+9]) == terceiro_oficial:

            bonus += 12


        if limpar(C_Palpites.iloc[127,inicio+9]) == quarto_oficial:

            bonus += 10



    linha_resultado[

        "Campeão/Vice/3º/4º"

    ] = bonus



    total += bonus


    linha_resultado[

        "ITEM 4.2 TOTAL"

    ] = total



    resultado.append(

        linha_resultado

    )



# ============================================================
# DATAFRAME ITEM 4.2
# ============================================================

DF_ITEM_4_2 = pd.DataFrame(resultado)



# ============================================================
# ATUALIZAR RANKING
# ============================================================

mapa = (

    DF_ITEM_4_2

    .set_index("Participante")

    ["ITEM 4.2 TOTAL"]

)



DF_RANKING_OFICIAL[

    "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º"

] = (

    DF_RANKING_OFICIAL["Participante"]

    .map(mapa)

    .fillna(0)

    .astype(int)

)



DF_RANKING_OFICIAL["TOTAL"] = (


    DF_RANKING_OFICIAL[
        "ITEM 4.1. Fase de Grupo"
    ]

    +

    DF_RANKING_OFICIAL[
        "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º"
    ]

    +

    DF_RANKING_OFICIAL[
        "4.2. Artilheiro"
    ]

    +

    DF_RANKING_OFICIAL[
        "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias"
    ]

)



# ============================================================
# AUDITORIA
# ============================================================


display(DF_ITEM_4_2)

display(DF_RANKING_OFICIAL)


print("="*90)
print("🏆 BLOCO 6D FINAL v4 HOMOLOGADO PELO REGULAMENTO")
print("="*90)

# ============================================================
# BLOCO 6E FINAL v3 — ARTILHEIRO FIFA OFICIAL
# ITEM 4.2 REGULAMENTO
# FIFA PREMIUM v2.0
# ============================================================

import pandas as pd


print("="*90)
print("⚽ BLOCO 6E FINAL v3 — ARTILHEIRO FIFA")
print("="*90)



# ============================================================
# FUNÇÕES
# ============================================================

def limpar_nome(valor):

    return (

        str(valor)

        .strip()

        .upper()

    )



def valido(nome):

    return nome not in [

        "",
        "NAN",
        "ARTILHEIRO:",
        "ARTILHEIRO",
        "A DEFINIR"

    ]



# ============================================================
# ARTILHEIRO OFICIAL
# ============================================================

ARTILHEIRO_OFICIAL = limpar_nome(

    C_Placares_Oficiais.iloc[122,9]

)



# ============================================================
# PARTICIPANTES
# ============================================================

resultado = []


TOTAL = 30

SALTO = 10



for i in range(TOTAL):


    inicio = i * SALTO


    coluna = inicio + 9



    participante = (

        str(C_Palpites.columns[inicio])

        .replace(" Status","")

        .strip()

    )



    palpite = limpar_nome(

        C_Palpites.iloc[122,coluna]

    )



    pontos = 0



    if (

        valido(ARTILHEIRO_OFICIAL)

        and

        palpite == ARTILHEIRO_OFICIAL

    ):

        pontos = 20



    resultado.append(

        {

            "Participante":

                participante,


            "Palpite Artilheiro":

                palpite,


            "Artilheiro Oficial":

                ARTILHEIRO_OFICIAL,


            "Pontos Artilheiro":

                pontos

        }

    )



# ============================================================
# DATAFRAME
# ============================================================

DF_ARTILHEIRO = pd.DataFrame(resultado)



# ============================================================
# ATUALIZA RANKING
# ============================================================

mapa = (

    DF_ARTILHEIRO

    .set_index("Participante")

    ["Pontos Artilheiro"]

)



DF_RANKING_OFICIAL[

    "4.2. Artilheiro"

] = (

    DF_RANKING_OFICIAL["Participante"]

    .map(mapa)

    .fillna(0)

    .astype(int)

)



# ============================================================
# RECALCULAR TOTAL
# ============================================================

DF_RANKING_OFICIAL["TOTAL"] = (


    DF_RANKING_OFICIAL[

        "ITEM 4.1. Fase de Grupo"

    ]

    +

    DF_RANKING_OFICIAL[

        "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias"

    ]

    +

    DF_RANKING_OFICIAL[

        "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º"

    ]

    +

    DF_RANKING_OFICIAL[

        "4.2. Artilheiro"

    ]

)



# ============================================================
# AUDITORIA
# ============================================================


display(DF_ARTILHEIRO)

display(DF_RANKING_OFICIAL)



print("="*90)

print("🏆 BLOCO 6E FINAL v3 HOMOLOGADO")

print("="*90)

# ============================================================
# BLOCO 7A — RANKING FINAL OFICIAL
# PUBLICAÇÃO FIFA PREMIUM
# ============================================================

import pandas as pd


print("="*90)
print("🏆 BLOCO 7A — RANKING FINAL OFICIAL")
print("="*90)



# ============================================================
# CÓPIA SEGURA
# ============================================================

DF_RANKING_PUBLICO = DF_RANKING_OFICIAL.copy()



# ============================================================
# GARANTIA NUMÉRICA
# ============================================================

colunas_pontos = [

    "ITEM 4.1. Fase de Grupo",

    "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias",

    "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º",

    "4.2. Artilheiro"

]


for coluna in colunas_pontos:

    DF_RANKING_PUBLICO[coluna] = (

        pd.to_numeric(

            DF_RANKING_PUBLICO[coluna],

            errors="coerce"

        )

        .fillna(0)

        .astype(int)

    )



# ============================================================
# RECALCULA TOTAL FINAL
# ============================================================

DF_RANKING_PUBLICO["TOTAL"] = (

    DF_RANKING_PUBLICO[colunas_pontos]

    .sum(axis=1)

)



# ============================================================
# ORDENAÇÃO
# ============================================================

DF_RANKING_PUBLICO = (

    DF_RANKING_PUBLICO

    .sort_values(

        by="TOTAL",

        ascending=False

    )

    .reset_index(drop=True)

)



# ============================================================
# POSIÇÃO OFICIAL
# método min mantém empate real
# Exemplo:
# 1
# 1
# 3
# ============================================================

DF_RANKING_PUBLICO["Posição"] = (

    DF_RANKING_PUBLICO["TOTAL"]

    .rank(

        method="min",

        ascending=False

    )

    .astype(int)

)



# ============================================================
# APROVEITAMENTO
# ============================================================

PONTUACAO_MAXIMA = 1797


DF_RANKING_PUBLICO["Aproveitamento %"] = (

    DF_RANKING_PUBLICO["TOTAL"]

    /

    PONTUACAO_MAXIMA

    *

    100

).round(2)



# ============================================================
# ORGANIZA COLUNAS
# ============================================================

DF_RANKING_PUBLICO = DF_RANKING_PUBLICO[

    [

        "Posição",

        "Participante",

        "ITEM 4.1. Fase de Grupo",

        "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias",

        "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º",

        "4.2. Artilheiro",

        "TOTAL",

        "Aproveitamento %"

    ]

]



# ============================================================
# EXIBIÇÃO
# ============================================================


display(

    DF_RANKING_PUBLICO

)



print("="*90)

print(
    "🏆 RANKING FINAL GERADO COM SUCESSO"
)

print("="*90)

# ============================================================
# BLOCO 7B FINAL — PUBLICAÇÃO DAS TABELAS
# FIFA PREMIUM v2.0
# ============================================================

import pandas as pd


print("="*90)
print("🏆 BLOCO 7B FINAL — PUBLICAÇÃO")
print("="*90)



# ============================================================
# 1 — RANKING GERAL OFICIAL
# ============================================================

DF_PUBLICACAO_RANKING = (

    DF_RANKING_PUBLICO

    .copy()

)


print()
print("🏆 RANKING GERAL")

display(

    DF_PUBLICACAO_RANKING

)



# ============================================================
# 2 — PREMIAÇÃO FASE DE GRUPOS
# ============================================================

DF_PUBLICACAO_GRUPOS = (

    DF_PREMIACAO_GRUPOS

    .copy()

)



DF_PUBLICACAO_GRUPOS = (

    DF_PUBLICACAO_GRUPOS

    .sort_values(

        by="TOTAL PREMIAÇÃO FASE DE GRUPOS",

        ascending=False

    )

    .reset_index(drop=True)

)



DF_PUBLICACAO_GRUPOS["Posição"] = (

    DF_PUBLICACAO_GRUPOS[

        "TOTAL PREMIAÇÃO FASE DE GRUPOS"

    ]

    .rank(

        method="min",

        ascending=False

    )

    .astype(int)

)



print()
print("🥇 PREMIAÇÃO FASE DE GRUPOS")


display(

    DF_PUBLICACAO_GRUPOS

)



# ============================================================
# 3 — ESTATÍSTICAS DO BOLÃO
# ============================================================


total_participantes = len(

    DF_PUBLICACAO_RANKING

)



maior_pontuacao = (

    DF_PUBLICACAO_RANKING["TOTAL"]

    .max()

)



media_pontos = (

    DF_PUBLICACAO_RANKING["TOTAL"]

    .mean()

)



lideres = (

    DF_PUBLICACAO_RANKING[

        DF_PUBLICACAO_RANKING["TOTAL"]

        ==

        maior_pontuacao

    ]

    ["Participante"]

    .tolist()

)



DF_ESTATISTICAS_BOLAO = pd.DataFrame(

    [

        {

            "Participantes":

                total_participantes,


            "Líder(es)":

                ", ".join(lideres),


            "Maior Pontuação":

                maior_pontuacao,


            "Média Pontos":

                round(

                    media_pontos,

                    2

                ),


            "Teto Possível":

                1797

        }

    ]

)



print()
print("📊 ESTATÍSTICAS")


display(

    DF_ESTATISTICAS_BOLAO

)



print("="*90)

print(

    "🏆 BLOCO 7B FINAL HOMOLOGADO"

)

print("="*90)

# ============================================================
# BLOCO 7C — EXPORTAÇÃO FINAL PARA PRODUÇÃO
# FIFA PREMIUM v2.0
# ============================================================

import json
import os


print("="*90)
print("🚀 BLOCO 7C — EXPORTAÇÃO PARA PRODUÇÃO")
print("="*90)



# ============================================================
# CRIA PASTA DE SAÍDA
# ============================================================

PASTA_EXPORTACAO = "publicacao"


os.makedirs(

    PASTA_EXPORTACAO,

    exist_ok=True

)



# ============================================================
# 1 — EXPORTAR RANKING GERAL
# ============================================================

arquivo_ranking = (

    PASTA_EXPORTACAO

    +

    "/ranking_geral.json"

)


DF_PUBLICACAO_RANKING.to_json(

    arquivo_ranking,

    orient="records",

    force_ascii=False,

    indent=4

)



# ============================================================
# 2 — EXPORTAR PREMIAÇÃO FASE DE GRUPOS
# ============================================================

arquivo_grupos = (

    PASTA_EXPORTACAO

    +

    "/ranking_fase_grupos.json"

)


DF_PUBLICACAO_GRUPOS.to_json(

    arquivo_grupos,

    orient="records",

    force_ascii=False,

    indent=4

)



# ============================================================
# 3 — EXPORTAR ESTATÍSTICAS
# ============================================================

arquivo_estatisticas = (

    PASTA_EXPORTACAO

    +

    "/estatisticas_bolao.json"

)


DF_ESTATISTICAS_BOLAO.to_json(

    arquivo_estatisticas,

    orient="records",

    force_ascii=False,

    indent=4

)



# ============================================================
# AUDITORIA DOS ARQUIVOS
# ============================================================

arquivos = [

    arquivo_ranking,

    arquivo_grupos,

    arquivo_estatisticas

]


print()

for arquivo in arquivos:


    if os.path.exists(arquivo):

        print(
            "✅ Gerado:",
            arquivo
        )


    else:

        print(
            "❌ Falhou:",
            arquivo
        )



print()

print(
    "Arquivos disponíveis:",
    os.listdir(PASTA_EXPORTACAO)
)



print("="*90)

print(

    "🏆 BLOCO 7C FINALIZADO — EXPORTAÇÃO HOMOLOGADA"

)

print("="*90)

# ============================================================
# BLOCO 7D — AUDITOR DE PRODUÇÃO
# FIFA PREMIUM v2.0
# ============================================================

import os


print("="*90)
print("🔒 BLOCO 7D — AUDITOR DE PRODUÇÃO")
print("="*90)



ERROS = []
ALERTAS = []



# ============================================================
# 1 — EXISTÊNCIA DOS DATAFRAMES PRINCIPAIS
# ============================================================

obrigatorios = {

    "DF_RANKING_PUBLICO":
        "Bloco 7A",

    "DF_PUBLICACAO_RANKING":
        "Bloco 7B",

    "DF_PUBLICACAO_GRUPOS":
        "Bloco 7B / Premiação grupos",

    "DF_ESTATISTICAS_BOLAO":
        "Bloco 7B",

}


for nome, origem in obrigatorios.items():


    if nome not in globals():


        ERROS.append(

            f"{nome} não encontrado | Verificar {origem}"

        )



# ============================================================
# 2 — PARTICIPANTES
# ============================================================

try:


    qtd = len(

        DF_PUBLICACAO_RANKING

    )


    if qtd != 30:


        ERROS.append(

            f"Quantidade de participantes = {qtd}. Esperado: 30 | Verificar importação dos participantes"

        )


    else:


        print(
            "✅ Participantes:",
            qtd
        )



except Exception as e:


    ERROS.append(

        "Não foi possível validar participantes"

    )



# ============================================================
# 3 — COLUNAS OBRIGATÓRIAS
# ============================================================


colunas_obrigatorias = [

    "Posição",

    "Participante",

    "ITEM 4.1. Fase de Grupo",

    "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias",

    "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º",

    "4.2. Artilheiro",

    "TOTAL"

]



try:


    for coluna in colunas_obrigatorias:


        if coluna not in DF_PUBLICACAO_RANKING.columns:


            ERROS.append(

                f"Coluna ausente: {coluna} | Verificar 7A"

            )


except:


    ERROS.append(

        "Falha ao conferir colunas do ranking"

    )



# ============================================================
# 4 — VALIDAÇÃO DO TOTAL
# ============================================================


try:


    soma = (

        DF_PUBLICACAO_RANKING[

            [

                "ITEM 4.1. Fase de Grupo",

                "ITEM 4.3. e 5 - Confrontos Fase Eliminatórias",

                "ITEM 4.2. Passagem de fase, Campeão, Vice, 3º e 4º",

                "4.2. Artilheiro"

            ]

        ]

        .sum(axis=1)

    )


    if not (

        soma

        ==

        DF_PUBLICACAO_RANKING["TOTAL"]

    ).all():


        ERROS.append(

            "TOTAL divergente da soma dos itens | Verificar motores 6B / 6D / 6E"

        )


    else:


        print(

            "✅ Soma do TOTAL validada"

        )



except Exception:


    ERROS.append(

        "Erro ao validar TOTAL"

    )



# ============================================================
# 5 — LIMITE DO REGULAMENTO
# ============================================================


try:


    acima = (

        DF_PUBLICACAO_RANKING[

            DF_PUBLICACAO_RANKING["TOTAL"] > 1797

        ]

    )


    if len(acima) > 0:


        ERROS.append(

            "Participante ultrapassou 1797 pontos | Revisar pontuação"

        )


    else:


        print(

            "✅ Limite máximo 1797 respeitado"

        )



except:


    ERROS.append(

        "Erro ao conferir teto máximo"

    )



# ============================================================
# 6 — ARQUIVOS JSON
# ============================================================


arquivos = [

    "publicacao/ranking_geral.json",

    "publicacao/ranking_fase_grupos.json",

    "publicacao/estatisticas_bolao.json"

]



for arquivo in arquivos:


    if not os.path.exists(arquivo):


        ERROS.append(

            f"Arquivo não criado: {arquivo} | Verificar 7C"

        )


    else:


        print(

            "✅ JSON encontrado:",

            arquivo

        )



# ============================================================
# RESULTADO FINAL
# ============================================================


print()
print("-"*90)


if len(ERROS) == 0:


    print(

        "🏆 SISTEMA APROVADO PARA PRODUÇÃO"

    )


else:


    print(

        "❌ PENDÊNCIAS ENCONTRADAS"

    )


    print()


    for erro in ERROS:


        print(

            "➡️",

            erro

        )



if ALERTAS:


    print()

    print(

        "⚠️ ALERTAS"

    )


    for alerta in ALERTAS:


        print(

            "-",

            alerta

        )



print("="*90)

# ============================================================
# BLOCO 8A — EXPORTADOR MOTOR.PY
# GERA ARQUIVO BASE PARA RENDER
# ============================================================

import os
import shutil


print("="*90)
print("🚀 BLOCO 8A — EXPORTADOR MOTOR.PY")
print("="*90)


# ============================================================
# CRIA PASTA DO PROJETO
# ============================================================

PASTA_RENDER = "bolao_copa_2026_render"


os.makedirs(
    PASTA_RENDER,
    exist_ok=True
)



# ============================================================
# LOCALIZA NOTEBOOK ATUAL
# ============================================================

print()
print("📁 Estrutura criada:")


pastas = [

    PASTA_RENDER,

    PASTA_RENDER + "/dados",

    PASTA_RENDER + "/publicacao"

]


for pasta in pastas:

    os.makedirs(
        pasta,
        exist_ok=True
    )

    print("✅", pasta)



# ============================================================
# COPIA JSONS HOMOLOGADOS
# ============================================================

origem = "publicacao"


if os.path.exists(origem):


    for arquivo in os.listdir(origem):


        shutil.copy(

            origem + "/" + arquivo,

            PASTA_RENDER + "/publicacao/" + arquivo

        )


        print(
            "✅ Copiado:",
            arquivo
        )



# ============================================================
# CRIA MOTOR BASE
# ============================================================


conteudo_motor = """

# ============================================================
# MOTOR BOLÃO COPA 2026
# GERADO A PARTIR DO COLAB HOMOLOGADO
# ============================================================


def executar_motor():

    print("🏆 Motor iniciado")

    # Aqui entrarão os blocos:
    # 6A
    # 5.6
    # 5.7
    # 6C
    # 6B
    # 6D
    # 6E
    # 7A
    # 7B
    # 7C
    # 7D

    print("🏆 Motor finalizado")


if __name__ == "__main__":

    executar_motor()

"""


with open(

    PASTA_RENDER + "/motor.py",

    "w",

    encoding="utf-8"

) as f:


    f.write(

        conteudo_motor

    )



print()
print("✅ motor.py criado")



print("="*90)
print("🏆 ESTRUTURA BASE DO RENDER CRIADA")
print("="*90)

# ============================================================
# BLOCO 8B — EXPORTAÇÃO DO NOTEBOOK HOMOLOGADO
# ============================================================

import os


print("="*90)
print("🚀 BLOCO 8B — PREPARAÇÃO DO MOTOR REAL")
print("="*90)



# ============================================================
# VERIFICA ESTRUTURA
# ============================================================

pasta = "bolao_copa_2026_render"


if os.path.exists(pasta):

    print(
        "✅ Pasta Render encontrada"
    )


else:

    print(
        "❌ Pasta Render não encontrada"
    )



# ============================================================
# LISTAGEM PARA CONFERÊNCIA
# ============================================================

print()
print("📁 Arquivos atuais:")


for raiz, pastas, arquivos in os.walk(pasta):


    nivel = raiz.replace(pasta, "").count(os.sep)


    espaco = " " * 4 * nivel


    print(
        espaco,
        os.path.basename(raiz),
        "/"
    )


    for arquivo in arquivos:


        print(
            espaco,
            "   -",
            arquivo
        )



print("="*90)
print("🏆 AMBIENTE PRONTO PARA RECEBER MOTOR")
print("="*90)